---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeeves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jeeves
  template:
    metadata:
      labels:
        app: jeeves
    spec:
      serviceAccount: jeeves
      containers:
        - name: jeeves
          image: containersol/jeeves
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          env:
          - name: SERVER_HOST
            value: 0.0.0.0
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: slackauth
                key: SLACK_SIGNING_SECRET
          - name: SLACK_AUTHENTICATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: slackauth
                key: SLACK_AUTHENTICATION_TOKEN
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

