apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jeeves
resources:
- secrets.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
