---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jeeves
subjects:
- kind: ServiceAccount
  name: jeeves
  namespace: jeeves
roleRef:
  kind: Role
  name: jeeves
  apiGroup: rbac.authorization.k8s.io
