apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jeeves
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["jobs"]
  verbs: ["delete", "watch", "list", "create"]
