---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jeeves
spec:
  rules:
  - host: jeeves-test.apps.csol.cloud
    http:
      paths:
      - backend:
          serviceName: jeeves
          servicePort: 80
        path: /
  tls:
  - hosts:
    - jeeves-test.apps.csol.cloud
    secretName: jeeves-test-tls
