apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jeeves-test
resources:
- ../base/
- secrets.yaml
patchesStrategicMerge:
- ingress.patch.yaml
- rolebinding.patch.yaml
images:
- name: containersol/jeeves
  newName: containersol/jeeves
  newTag: edge
